version: 0.2

phases:
    build:
        commands:
            - echo "Checking the python versions"
            - pyenv install —-list | grep " 3\.[78]" 
artifacts:
   files:
      - template.json
   name: test-$(date +%Y-%m-%d)
        
  
