version: 0.2

phases:
    pre_build:
        commands:
             - sudo apt-get update -y
    build:
        commands:
            - echo Entered the build phase...
            - echo "Hello, there!" > hello.txt
artifacts:
   files:
      - template.json
      - hello.txt
   name: test-$(date +%Y-%m-%d)
        
  
