version: 0.2

phases:
    pre_build:
        commands:
             - sudo apt-get update -y
    build:
        commands:
            - echo Entered the build phase...
artifacts:
   files:
      - template.json
   name: test-$(date +%Y-%m-%d)
        
  
